Data download and setting environment
WayScience/gene_dependency_representations pull request #3
Opened 2022-06-15 21:11 UTC by mjw-18

2022-06-15 21:39 UTC, mjw-18 commented
@gwaybio Hey Greg! This pull request is now ready for review.

2022-06-16 13:31 UTC, gwaybio requested changes
Thanks for your PR @mjw-18 ! Nice work!

Let's discuss the several comments I made.

I'll review the data downloader notebook after you provide the nbconverted file (see comment below)

2022-06-16 13:31 UTC, gwaybio commented on .gitignore
> +data/
```suggestion
0.data-download/data/*

```

To be more specific about which data folder. We might want to include other data in other folders in the future.

Also, I'm adding an extra new line character to the end of the file. This removes the red warning label at the end of line two.

p.s. - See [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) for instructions on how to accept "suggestions" into your  PR.

2022-06-16 13:31 UTC, gwaybio commented on 0.data-download/data_downloader.ipynb
> +{
Jupyter notebook files (`.ipynb`) are [JSON formatted](https://ipython.org/ipython-doc/3/notebook/nbformat.html), which makes them difficult to review.

For this reason, we always include two copies of all notebooks:

1. the `.ipynb` version you've included here
2. an `nbconverted` `.py` version you need to add

To create the `.py` version, run the following command:

```bash
# Activate your conda environment
conda activate __NAME__

# Navigate to the proper folder
cd 0.data-download

# Run nbconvert to create a .py file
jupyter nbconvert --to=script --FilesWriter.build_directory=scripts/nbconverted *.ipynb
```

Please add, commit, push this nbconverted file to this PR, and I will review this file.

2022-06-16 13:31 UTC, gwaybio commented on LICENSE.md
> +Copyright (c) 2022, Way Laboratory All rights reserved.
This is ok for now - thanks!

2022-06-16 13:31 UTC, gwaybio commented on environment.yml
> +- conda-forge::jupyterlab	=	3.4.3
Keep this package

2022-06-16 13:31 UTC, gwaybio commented on environment.yml
> +- conda-forge::python	=	3.9.13
keep this line

2022-06-16 13:31 UTC, gwaybio commented on environment.yml
> +- conda-forge::urllib3	=	1.26.9
keep this line

2022-06-16 13:31 UTC, gwaybio commented on environment.yml
> +name: gene_dependency_representations
It is poor practice to add all packages to the conda environment - I have found that doing so is far too rigid, making "solving the environment" far to restricted, and is likely to fail in a short amount of time and/or in different operating systems. I have been guilty of this in the past!

Please delete all `dependencies` except the three I highlighted. Only add a critical dependency when you need to use a new package.

2022-06-16 15:32 UTC, mjw-18 commented
@gwaybio I believe I have performed the requested updates correctly! let me know if these check out!

2022-06-16 15:49 UTC, gwaybio commented
i see the `.py` file, but I don't see the updates in the `environment.yml`. I'll take a look at the .py file now!

2022-06-16 17:57 UTC, gwaybio requested changes
Make sure your notebook starts with the first cell executed first (right now it is `2`), and trim your conda env file a bit more

2022-06-16 17:57 UTC, gwaybio commented on 0.data-download/scripts/nbconverted/data_downloader.py
> +# In[2]:
Looks like you will have to _reset kernel and run all_ again. This should be executed first.

2022-06-16 17:57 UTC, gwaybio commented on environment.yml
> +- conda-forge::jupyterlab	=	3.4.3
```suggestion
- conda-forge::jupyterlab=3.4.3
```

2022-06-16 17:57 UTC, gwaybio commented on environment.yml
> +- conda-forge::python	=	3.9.13
```suggestion
- conda-forge::python=3.9.13
```

2022-06-16 17:57 UTC, gwaybio commented on environment.yml
> +- conda-forge::urllib3	=	1.26.9
```suggestion
- conda-forge::urllib3=1.26.9

```

2022-06-16 21:39 UTC, gwaybio approved these changes
Wonderful. Nice work!

2022-06-16 22:13 UTC, merged